= KeePassXC Settings
Jordan Williams <jordan@jwillikers.com>
:experimental:
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:keepassxc: https://keepassxc.org/[KeePassXC]

My settings for the {keepassxc} password manager.

== Usage

This repository contains the settings file for KeePassXC.
This file is synchronized using this Git repository.
The following instructions detail how to use and sync this repository.

=== Install

Install these settings with the following instructions.

. Clone this repository.
+
[,sh]
----
git clone git@github.com:jwillikers/keepassxc-config.git
----

. Change to the project's directory.
+
[,sh]
----
cd keepassxc-config
----

. Symlink the `keepassxc.ini` file to the appropriate location.
+
--
NOTE: Close KeePassXC before copying the settings file.

_Flatpak_::
+
[,sh]
----
ln --force --relative --symbolic keepassxc.ini \
  ~/.var/app/org.keepassxc.KeePassXC/config/keepassxc/keepassxc.ini
----

_System Package_::
+
[,sh]
----
ln --force --relative --symbolic keepassxc.ini \
  ~/.config/keepassxc/keepassxc.ini
----
--

== Code of Conduct

Please refer to the project's link:CODE_OF_CONDUCT.adoc[Code of Conduct].

== License

This repository is licensed under the https://www.gnu.org/licenses/gpl-3.0.html[GPLv3].
Please refer to the bundled link:LICENSE.adoc[license].

== Copyright

© 2020-2024 Jordan Williams

== Authors

mailto:{email}[{author}]
